# Generated by Django 5.2.8 on 2025-11-29 16:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(db_index=True, help_text='Subject area of expertise', max_length=200)),
                ('qualifications', models.TextField(help_text='Educational qualifications and certifications')),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], max_length=20)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], db_index=True, default='active', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly payment rate in DH', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_rate_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Tax percentage (e.g., 10 for 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('rib', models.CharField(blank=True, help_text="Relevé d'Identité Bancaire", max_length=24, null=True)),
                ('bio', models.TextField(blank=True, help_text='Brief biography', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
