# Generated by Django 5.2.8 on 2025-11-29 16:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True, null=True)),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_phone', models.CharField(db_index=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')])),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('education_level', models.CharField(choices=[('primary', 'Primary School'), ('middle', 'Middle School'), ('high', 'High School'), ('university', 'University'), ('other', 'Other')], max_length=20)),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_date', models.DateField(db_index=True, default=datetime.date.today)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('medical_notes', models.TextField(blank=True, help_text='Any medical conditions or allergies', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-registration_date', 'full_name'],
            },
        ),
    ]
