# Generated by Django 5.2.8 on 2025-11-29 16:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(db_index=True, max_length=200)),
                ('course_type', models.CharField(choices=[('academic', 'Academic Support'), ('language', 'Language Course'), ('skill', 'Skill Development'), ('exam_prep', 'Exam Preparation')], db_index=True, max_length=20)),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('fee_per_month', models.DecimalField(decimal_places=2, help_text='Monthly fee in DH', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_students', models.PositiveIntegerField(default=20, help_text='Maximum number of students', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_months', models.PositiveIntegerField(default=1, help_text='Course duration in months')),
                ('schedule_days', models.JSONField(default=list, help_text="List of days when course meets (e.g., ['monday', 'wednesday'])")),
                ('schedule_time', models.TimeField(help_text='Start time of the course')),
                ('hours_per_session', models.DecimalField(decimal_places=2, default=Decimal('1.5'), help_text='Duration of each session in hours', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))])),
                ('classroom', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date', 'course_name'],
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=True, help_text='Is this the primary instructor for the course?')),
                ('hours_taught', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total hours taught in this course', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instructors', to='courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_courses', to='instructors.instructor')),
            ],
            options={
                'ordering': ['-is_primary', 'assigned_date'],
                'indexes': [models.Index(fields=['course', 'instructor'], name='courses_cou_course__14b041_idx')],
                'unique_together': {('course', 'instructor')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Final grade (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'ordering': ['-enrollment_date'],
                'indexes': [models.Index(fields=['student', 'status'], name='courses_enr_student_c86bf5_idx'), models.Index(fields=['course', 'status'], name='courses_enr_course__78d524_idx'), models.Index(fields=['enrollment_date'], name='courses_enr_enrollm_eb8905_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
