# Generated by Django 5.2.8 on 2025-11-29 16:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('certificate', 'Certificate'), ('report', 'Report'), ('contract', 'Contract'), ('letter', 'Letter')], max_length=20)),
                ('html_template', models.TextField(help_text='HTML template with variables')),
                ('css_styles', models.TextField(blank=True, help_text='CSS styles for the template', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default template for this type?')),
                ('page_size', models.CharField(default='A4', help_text='Page size (A4, Letter, etc.)', max_length=10)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('variables_help', models.TextField(blank=True, help_text='Documentation of available variables', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'name'],
                'indexes': [models.Index(fields=['template_type', 'is_active'], name='documents_d_templat_e7a2c5_idx'), models.Index(fields=['is_default'], name='documents_d_is_defa_7699cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('certificate', 'Certificate'), ('report', 'Report'), ('contract', 'Contract'), ('id_document', 'ID Document'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('document_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('related_model', models.CharField(blank=True, help_text="Model name (e.g., 'student', 'instructor')", max_length=50, null=True)),
                ('related_id', models.IntegerField(blank=True, help_text='ID of the related object', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('sent', 'Sent'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('document_date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-document_date', '-created_at'],
                'indexes': [models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'), models.Index(fields=['document_number'], name='documents_d_documen_dbcf06_idx'), models.Index(fields=['related_model', 'related_id'], name='documents_d_related_760f27_idx'), models.Index(fields=['status'], name='documents_d_status_07369e_idx'), models.Index(fields=['document_date'], name='documents_d_documen_0eb394_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstructorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', 'ID Card'), ('resume', 'Resume/CV'), ('degree', 'Degree Certificate'), ('certificate', 'Professional Certificate'), ('contract', 'Employment Contract'), ('background_check', 'Background Check'), ('tax_form', 'Tax Form'), ('bank_info', 'Bank Information'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('upload_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='instructors.instructor')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_instructor_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_instructor_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['instructor', 'document_type'], name='documents_i_instruc_21878c_idx'), models.Index(fields=['is_verified'], name='documents_i_is_veri_d3fb86_idx'), models.Index(fields=['expiry_date'], name='documents_i_expiry__f2475a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('id_card', 'ID Card'), ('photo', 'Photo'), ('medical_certificate', 'Medical Certificate'), ('enrollment_form', 'Enrollment Form'), ('consent_form', 'Consent Form'), ('transcript', 'Academic Transcript'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('upload_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_student_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_student_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['student', 'document_type'], name='documents_s_student_db545f_idx'), models.Index(fields=['is_verified'], name='documents_s_is_veri_5a1490_idx'), models.Index(fields=['expiry_date'], name='documents_s_expiry__f8fa3d_idx')],
            },
        ),
    ]
