# Generated by Django 5.2.8 on 2025-11-29 16:47

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField(help_text='Budget month')),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('supplies', 'Supplies'), ('marketing', 'Marketing'), ('maintenance', 'Maintenance'), ('insurance', 'Insurance'), ('salaries', 'Salaries (non-instructor)'), ('taxes', 'Taxes'), ('other', 'Other')], max_length=20)),
                ('allocated_amount', models.DecimalField(decimal_places=2, help_text='Budgeted amount for the category', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_month', 'category'],
                'indexes': [models.Index(fields=['period_month', 'category'], name='financials__period__d76b6f_idx')],
                'unique_together': {('period_month', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('supplies', 'Supplies'), ('marketing', 'Marketing'), ('maintenance', 'Maintenance'), ('insurance', 'Insurance'), ('salaries', 'Salaries (non-instructor)'), ('taxes', 'Taxes'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('expense_date', models.DateField(default=datetime.date.today)),
                ('period_month', models.DateField(help_text='Assign to which financial month')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_image', models.CharField(blank=True, max_length=500, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['category'], name='financials__categor_fb78f8_idx'), models.Index(fields=['expense_date'], name='financials__expense_1310e0_idx'), models.Index(fields=['period_month'], name='financials__period__5a9f52_idx'), models.Index(fields=['status'], name='financials__status_78f57d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField(help_text='First day of the financial period month', unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total student payments received', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('instructor_payments', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total paid to instructors', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('operational_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Rent, utilities, supplies, etc.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('other_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('retained_earnings', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount kept as reserves', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('distributable_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount available for member distribution', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_finalized', models.BooleanField(default=False, help_text='Whether financial calculations are finalized')),
                ('finalized_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monthly Financial Summary',
                'verbose_name_plural': 'Monthly Financial Summaries',
                'ordering': ['-period_month'],
                'indexes': [models.Index(fields=['period_month'], name='financials__period__b198d6_idx'), models.Index(fields=['is_finalized'], name='financials__is_fina_76d482_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstructorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField(help_text='First day of the payment period month')),
                ('total_hours', models.DecimalField(decimal_places=2, help_text='Total hours worked in the period', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate at time of calculation', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Amount before taxes', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Tax withheld', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount after taxes', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='instructors.instructor')),
            ],
            options={
                'ordering': ['-period_month', 'instructor__full_name'],
                'indexes': [models.Index(fields=['instructor', 'period_month'], name='financials__instruc_9d4ae6_idx'), models.Index(fields=['period_month'], name='financials__period__016581_idx'), models.Index(fields=['status'], name='financials__status_c7de7b_idx'), models.Index(fields=['payment_date'], name='financials__payment_1d20f5_idx')],
                'unique_together': {('instructor', 'period_month')},
            },
        ),
        migrations.CreateModel(
            name='MemberDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percentage', models.DecimalField(decimal_places=2, help_text="Member's share percentage at time of distribution", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount', models.DecimalField(decimal_places=2, help_text='Distribution amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('is_public_employee', models.BooleanField(default=False, help_text='Public employees cannot receive distributions')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='members.member')),
                ('monthly_financial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='financials.monthlyfinancial')),
            ],
            options={
                'ordering': ['-monthly_financial__period_month', 'member__full_name'],
                'indexes': [models.Index(fields=['member', 'status'], name='financials__member__06eee4_idx'), models.Index(fields=['monthly_financial', 'status'], name='financials__monthly_c9aa8e_idx'), models.Index(fields=['status'], name='financials__status_d86218_idx')],
                'unique_together': {('member', 'monthly_financial')},
            },
        ),
    ]
