# Generated by Django 5.2.8 on 2025-11-29 16:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('financial', 'Financial Report'), ('attendance', 'Attendance Report'), ('enrollment', 'Enrollment Report'), ('student_performance', 'Student Performance Report'), ('instructor_performance', 'Instructor Performance Report'), ('revenue', 'Revenue Report'), ('expense', 'Expense Report'), ('profit_distribution', 'Profit Distribution Report'), ('custom', 'Custom Report')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('parameters', models.JSONField(default=dict, help_text='Report parameters (date ranges, filters, etc.)')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], default='pdf', max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, null=True)),
                ('next_generation_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with_email', models.EmailField(max_length=254)),
                ('access_token', models.CharField(max_length=100, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='reports.report')),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('report_type', models.CharField(choices=[('financial', 'Financial Report'), ('attendance', 'Attendance Report'), ('enrollment', 'Enrollment Report'), ('student_performance', 'Student Performance Report'), ('instructor_performance', 'Instructor Performance Report'), ('revenue', 'Revenue Report'), ('expense', 'Expense Report'), ('profit_distribution', 'Profit Distribution Report'), ('custom', 'Custom Report')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_parameters', models.JSONField(default=dict, help_text='Default parameters for this report type')),
                ('template_content', models.TextField(blank=True, help_text='HTML/template content for the report', null=True)),
                ('css_styles', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('required_permissions', models.JSONField(default=list, help_text='Required permissions to generate this report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['report_type', 'name'],
                'indexes': [models.Index(fields=['report_type', 'is_active'], name='reports_rep_report__11a031_idx'), models.Index(fields=['is_default'], name='reports_rep_is_defa_5d5bcb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('parameters', models.JSONField(default=dict)),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses to send report to')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_run_date', models.DateField()),
                ('last_run_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('successful_runs', models.PositiveIntegerField(default=0)),
                ('failed_runs', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_schedules', to=settings.AUTH_USER_MODEL)),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['next_run_date'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='reports_rep_report__dbb097_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_rep_status_c732ef_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_by'], name='reports_rep_generat_4dc4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_scheduled', 'next_generation_date'], name='reports_rep_is_sche_4637e8_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['start_date', 'end_date'], name='reports_rep_start_d_29aaa5_idx'),
        ),
        migrations.AddIndex(
            model_name='reportshare',
            index=models.Index(fields=['report', 'is_active'], name='reports_rep_report__d2ff03_idx'),
        ),
        migrations.AddIndex(
            model_name='reportshare',
            index=models.Index(fields=['access_token'], name='reports_rep_access__3a7ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='reportshare',
            index=models.Index(fields=['expires_at'], name='reports_rep_expires_fc1cec_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['status', 'next_run_date'], name='reports_rep_status_f97eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['frequency'], name='reports_rep_frequen_1e97ea_idx'),
        ),
    ]
