# Generated by Django 5.2.8 on 2025-11-29 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('payment_reminder', 'Payment Reminder'), ('payment_received', 'Payment Received'), ('enrollment_confirmed', 'Enrollment Confirmed'), ('attendance_alert', 'Attendance Alert'), ('course_update', 'Course Update'), ('financial_report', 'Financial Report'), ('system_alert', 'System Alert'), ('general', 'General')], max_length=30)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push Notification'), ('in_app', 'In-App')], max_length=20)),
                ('recipient_type', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('instructor', 'Instructor'), ('member', 'Member'), ('admin', 'Admin')], help_text='Type of recipient', max_length=20)),
                ('recipient_id', models.IntegerField(help_text='ID of the recipient')),
                ('recipient_contact', models.CharField(help_text='Email or phone number', max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_attempts', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('related_model', models.CharField(blank=True, max_length=50, null=True)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_type', 'recipient_id'], name='notificatio_recipie_e8689e_idx'), models.Index(fields=['status'], name='notificatio_status_d92267_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['scheduled_time'], name='notificatio_schedul_c4290c_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_payment_reminders', models.BooleanField(default=True)),
                ('email_enrollment_updates', models.BooleanField(default=True)),
                ('email_attendance_alerts', models.BooleanField(default=True)),
                ('email_financial_reports', models.BooleanField(default=True)),
                ('email_system_alerts', models.BooleanField(default=True)),
                ('sms_payment_reminders', models.BooleanField(default=True)),
                ('sms_enrollment_updates', models.BooleanField(default=False)),
                ('sms_attendance_alerts', models.BooleanField(default=True)),
                ('sms_financial_reports', models.BooleanField(default=False)),
                ('sms_system_alerts', models.BooleanField(default=True)),
                ('push_payment_reminders', models.BooleanField(default=True)),
                ('push_enrollment_updates', models.BooleanField(default=True)),
                ('push_attendance_alerts', models.BooleanField(default=True)),
                ('push_financial_reports', models.BooleanField(default=False)),
                ('push_system_alerts', models.BooleanField(default=True)),
                ('preferred_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('preferred_phone', models.CharField(blank=True, max_length=17, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('payment_reminder', 'Payment Reminder'), ('payment_received', 'Payment Received'), ('enrollment_confirmed', 'Enrollment Confirmed'), ('attendance_alert', 'Attendance Alert'), ('course_update', 'Course Update'), ('financial_report', 'Financial Report'), ('system_alert', 'System Alert'), ('general', 'General')], max_length=30)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push Notification'), ('in_app', 'In-App')], max_length=20)),
                ('subject_template', models.CharField(blank=True, help_text='Subject template with variables like {student_name}', max_length=200, null=True)),
                ('message_template', models.TextField(help_text='Message template with variables like {amount}, {due_date}, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('variables_help', models.TextField(blank=True, help_text='Documentation of available variables', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['notification_type', 'name'],
                'indexes': [models.Index(fields=['notification_type', 'channel'], name='notificatio_notific_1005f2_idx'), models.Index(fields=['is_active'], name='notificatio_is_acti_b2a982_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('failed', 'Failed'), ('bounced', 'Bounced')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['notification', 'event_type'], name='notificatio_notific_2fbf05_idx'), models.Index(fields=['timestamp'], name='notificatio_timesta_eacc48_idx')],
            },
        ),
    ]
